Assets:
  Bundles:
    CSS:
      'Twitter.Bootstra:Bootstrap':
        'resource://Twitter.Bootstrap/Public/less/variables.less': 
          After: 
            - 'resource://Demo.ContentManagement/Public/less/variables.less'

TYPO3:
  TYPO3CR:
    contentTypes:
      'TYPO3.TYPO3:Page':
        Active: true
      'TYPO3.TYPO3:Text':
        Active: true

Foo:
  ContentManagement:
    Annotations:
      TYPO3\TYPO3\Domain\Model\User:
        active: true
        Properties: 
          name: 
            Inline: Foo.ContentManagement:InlineSeamless
          electronicAddresses:
            Ignore: true
          preferences:
            Ignore: true
          accounts:
            Inline: Foo.ContentManagement:InlineSeamless
      TYPO3\Party\Domain\Model\PersonName:
        Properties:
          title:
            Ignore: true
          otherName:
            Ignore: true
          middleName:
            Ignore: true
          fullName:
            Ignore: true
          alias:
            Ignore: true
      TYPO3\FLOW3\Security\Account:
        Properties:
          accountIdentifier:
            Title: true
          credentialsSource:
            Label: Passwort
          roles:
            Ignore: true
          creationDate:
            Ignore: true
          party:
            Ignore: true
          expirationDate:
            Ignore: true
          authenticationProviderName:
            Ignore: true
      TYPO3\Party\Domain\Model\ElectronicAddress:
        Properties:
          type:
            Element: TYPO3.Form:SingleSelectDropdown
            OptionsProvider: 
              Name: ConstOptionsProvider
              RegEx: TYPE_.+
          usage:
            Element: TYPO3.Form:SingleSelectDropdown
            OptionsProvider: 
              Name: ConstOptionsProvider
              RegEx: USAGE_.+